### ISSUE TITLE
Track Amount Waring Sign

### ISSUE THREAD

**Issue by CreatingCalifornia** [Gamearoo-s-Development/Usefull-Signs#18]
Add the sign as shown in the picture with custom text to change track amount
![IMG_2811](https://github.com/Gamearoo-s-Development/Usefull-Signs/assets/156473479/6bcd0e70-349b-41ff-be20-6a7ce20fec63)
![Uploading IMG_2809.png…]()

**Comment by GamearooCodes** [comment]
this is in another signpack already and with usefull signs being a roadside signpack not for rail or rail crossings this wont be added
