### ISSUE TITLE
LA County “N” signs

### ISSUE THREAD

**Issue by CreatingCalifornia** [Gamearoo-s-Development/Usefull-Signs#19]
Add this Los Angeles County, California route sign. Preferably with only a changeable number not a changeable letter.
![Uploading IMG_2815.png…]()

**Comment by GamearooCodes** [comment]
this seems to be a dupicate of https://github.com/Gamearoo-s-Development/Usefull-Signs/issues/9 if this is not you can open a new suggestion with a woring image
