### ISSUE TITLE
Tons of School Zone signs to consider

### ISSUE THREAD

**Issue by CreatingCalifornia** [Gamearoo-s-Development/Usefull-Signs#24]
I know some are already added, but here are some pictures of signs that you may won’t to pick at
![IMG_3026](https://github.com/Gamearoo-s-Development/Usefull-Signs/assets/156473479/edb8708b-56be-4615-8e02-70764339366b)
![Uploading IMG_3030.jpeg…]()

**Comment by GamearooCodes** [comment]
dupicate of https://github.com/Gamearoo-s-Development/Usefull-Signs/issues/25
