### ISSUE TITLE
Tons of School Zone signs to consider

### ISSUE THREAD

**Issue by CreatingCalifornia** [Gamearoo-s-Development/Usefull-Signs#25]
I know some are already added, but here are some pictures of signs that you may won’t to pick at
![IMG_3026](https://github.com/Gamearoo-s-Development/Usefull-Signs/assets/156473479/edb8708b-56be-4615-8e02-70764339366b)

**Comment by GamearooCodes** [comment]
the speed sign ahead is in the next version sadly for the rest you will need to reopen a new issue/suggestion
