### ISSUE TITLE
Text Color Chane

### ISSUE THREAD

**Issue by CreatingCalifornia** [Gamearoo-s-Development/Usefull-Signs#28]
As like with the old bug with the warning signs, from far distances on the nighttime speed limit sign, the text shows up white, but when you come closer to it, it turns gray for whatever reason. I don’t know if this is a similar problem to the handicap signs, but I know this problem was fixed with the warning science and I hope it could be fixed with this one too.
![Uploading IMG_3524.jpeg…]()

**Comment by CreatingCalifornia** [comment]
I do want to add, this problem seems to only be happening sometimes for what ever reason.

**Comment by GamearooCodes** [comment]
im unable to fix this as its a issue with mc Coloring tho every update realease a slightly diffrent  color choice in hopes to prevent this
