### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by CreatingCalifornia** [Gamearoo-s-Development/Usefull-Signs#4]
Can someone try to make all of these state law pedestrian signs for more realistic school zones, and for other applications. You could also make the long horizontal one custom text so you could change it from yield to stop.
![IMG_2276](https://github.com/Gamearoo-s-Development/Usefull-Signs/assets/156473479/bd6feebe-3cc8-4f8f-a79c-b97ab908c757)

**Comment by GamearooCodes** [comment]
Hello I'm messaging to let you know that this will be coming soon we are in the works for the next version

**Comment by CreatingCalifornia** [comment]
Hello There, really appreciate the message and I can’t wait to see this
design and thank you for taking it into consideration

**Comment by GamearooCodes** [comment]
In v6
