### ISSUE TITLE
Double Left Turn Signs

### ISSUE THREAD

**Issue by CreatingCalifornia** [Gamearoo-s-Development/Usefull-Signs#6]
Add a variety of double left turn signs for intersections with double left turn lanes
![IMG_2329](https://github.com/Gamearoo-s-Development/Usefull-Signs/assets/156473479/c7115788-cea8-4cd7-98e0-db967aafdbcc)
![Uploading IMG_2328.jpeg…]()

**Comment by GamearooCodes** [comment]
This has been added
