### ISSUE TITLE
Stop/Yield for pedestrians, and keep right except to pass signs

### ISSUE THREAD

**Issue by Hawkins001** [Gamearoo-s-Development/Usefull-Signs#7]
Pedestrian signs, 'Stop/Yield for Pedestrians in crosswalk' With 'State Law' on the signs.
![image_2024-01-21_134815262](https://github.com/Gamearoo-s-Development/Usefull-Signs/assets/136619988/e3beb60a-1d9f-4630-89f6-e842c1850ad9)

 'State Law Keep right Except to pass' Sign
 
![image_2024-01-21_135053590](https://github.com/Gamearoo-s-Development/Usefull-Signs/assets/136619988/8a6b922d-8d0a-40c8-a70f-9cf2a3aff3b7)
![image_2024-01-21_135103380](https://github.com/Gamearoo-s-Development/Usefull-Signs/assets/136619988/20ac26d3-3717-4fea-91cf-2748bcac6a8c)

Put these on here since they were directed to be put on here.

**Comment by GamearooCodes** [comment]
in v6
