### ISSUE TITLE
California Shield

### ISSUE THREAD

**Issue by CreatingCalifornia** [Gamearoo-s-Development/Usefull-Signs#9]
Please add the California shield for highways. It could be made as an individual version and there can be one compatible for this sign pack https://discord.com/channels/541808000537591821/1198964186135408650
![IMG_2272](https://github.com/Gamearoo-s-Development/Usefull-Signs/assets/156473479/8feb3fac-0baa-4d67-8f9c-3a73fb92a684)

**Comment by GamearooCodes** [comment]
after some time thinking if i do this state others will want other states its too much time for me to work on them for this pack however you can dm me for custom inqurays or custom packs related to what cant be added to this pack and we can work something out for you
